import os

REACT_APP_URL = os.getenv('REACT_APP_URL')
SQLALCHEMY_DATABASE_URI = "sqlite:///project.db"

DISCORD_CLIENT_ID = os.getenv('DISCORD_CLIENT_ID')
DISCORD_CLIENT_SECRET = os.getenv('DISCORD_CLIENT_SECRET')
DISCORD_REDIRECT_URI = os.getenv('DISCORD_REDIRECT_URI')
STEAM_CLIENT_ID = os.getenv('STEAM_CLIENT_ID')
STEAM_CLIENT_SECRET = os.getenv('STEAM_CLIENT_SECRET')
SECRET_KEY = os.getenv('SECRET_KEY')
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
