import os

DISCORD_CLIENT_ID = os.getenv('DISCORD_CLIENT_ID')
DISCORD_CLIENT_SECRET = os.getenv('DISCORD_CLIENT_SECRET')
DISCORD_REDIRECT_URI = os.getenv('DISCORD_REDIRECT_URI')
STEAM_CLIENT_ID = os.getenv('STEAM_CLIENT_ID')
STEAM_CLIENT_SECRET = os.getenv('STEAM_CLIENT_SECRET')
SECRET_KEY = os.getenv('SECRET_KEY')
