"""Add user ratings

Revision ID: 0af398ca8466
Revises: 3d3f561a4d72
Create Date: 2024-11-21 22:45:05.274025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af398ca8466'
down_revision = '3d3f561a4d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_user_id', sa.Integer(), nullable=False),
    sa.Column('rated_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rated_user_id'], ['user.id'], name=op.f('fk_rating_rated_user_id_user')),
    sa.ForeignKeyConstraint(['rating_user_id'], ['user.id'], name=op.f('fk_rating_rating_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating'))
    )
    op.create_table('rating_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ATTITUDE', 'COMMUNICATION', 'RELIABILITY', 'TEAMWORK', name='ratingfieldname'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], name=op.f('fk_rating_field_rating_id_rating')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating_field'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_field')
    op.drop_table('rating')
    # ### end Alembic commands ###
