"""Comment threads

Revision ID: 3d3f561a4d72
Revises: 2b058ce426ae
Create Date: 2024-11-14 20:49:52.423655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3f561a4d72'
down_revision = '2b058ce426ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_parent_id_comment'), 'comment', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_parent_id_comment'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
